// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXxUsufnCXGFWmnajUpM6cwg1rXsCAAFY',
    appId: '1:140466190705:web:12a9ae0beed36edec75ed0',
    messagingSenderId: '140466190705',
    projectId: 'tiktok-b343d',
    authDomain: 'tiktok-b343d.firebaseapp.com',
    storageBucket: 'tiktok-b343d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDuCNAASnuHmowy1IKdCkigT366EDZik0',
    appId: '1:140466190705:android:80626b513f738ad1c75ed0',
    messagingSenderId: '140466190705',
    projectId: 'tiktok-b343d',
    storageBucket: 'tiktok-b343d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOhZNvcwIWMKAZ2rocB5hlGgJfKNhg_iQ',
    appId: '1:140466190705:ios:96fed6aa64fc3f37c75ed0',
    messagingSenderId: '140466190705',
    projectId: 'tiktok-b343d',
    storageBucket: 'tiktok-b343d.appspot.com',
    iosClientId: '140466190705-pnjhkeu5j31im1qpn975mb83oq0268m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOhZNvcwIWMKAZ2rocB5hlGgJfKNhg_iQ',
    appId: '1:140466190705:ios:96fed6aa64fc3f37c75ed0',
    messagingSenderId: '140466190705',
    projectId: 'tiktok-b343d',
    storageBucket: 'tiktok-b343d.appspot.com',
    iosClientId: '140466190705-pnjhkeu5j31im1qpn975mb83oq0268m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );
}
